# server:
#   port:
#     8083

spring:
  application:
    name: user-service
  profiles:
    active: dev
  config:
    import: configserver:http://root:s3cr3t@localhost:8888

  # cloud:
  #   consul:
  #     host: localhost
  #     port: 8500
  #     discovery:
  #       service-name: ${spring.application.name}
  #       instance-id: ${spring.application.name}:${random.uuid}
  #       health-check-path: "/actuator/health"

# management:
#   endpoints:
#     web:
#       exposure:
#         include:
#           - health
application:
  jwt:
    secret: "m0N_Sup3R_C0d3_S3creT"
    expires: 86400000
    prefix: "Bearer "
    header: "Authorization"
