spring:
    # rabbitmq:
    #     host: localhost
    #     port: 5672
    #     username: david
    #     password: pass
  application:
      name: facture-service
  profiles:
    active: dev
  config:
    import: configserver:http://root:s3cr3t@localhost:8888
  cloud:
    stream:
      function:
        definition: recevoireservationenvoifacture
      bindings:
        recevoireservationenvoifacture-in-0:
          destination: messages.reservation
          binder: rabbit
          group: reservation
        recevoireservationenvoifacture-out-0:
          destination: messages.facture
          binder: rabbit
          group: facture
    # consul:
    #   host: localhost
    #   port: 8500
    #   discovery:
    #     service-name: ${spring.application.name}
    #     instance-id: ${spring.application.name}:${random.uuid}
        # health-check-path: "/actuator/health"
# management:
#   endpoints:
#     web:
#       exposure:
#         include:
#           - health
#           - beans
#           - mappings
#           - metrics
# server:
#     port: 8081