server:
  port: 8888

spring:
  security:
    user:
      name: root
      password: s3cr3t
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DavidRatz/config-repo
          default-label: main
          clone-on-start: true
